name: CI/CD Workflow for Mini Project 1

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_BUILDKIT: 1

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        # Эта строка берёт исходный код из репозитория GitHub.

      # Step 2: Build Docker image for backend_rds
      - name: Build Docker Image for Backend RDS
        run: |
          docker build -t mini_project_backend_rds -f backend_rds/Dockerfile backend_rds
          # Сборка Docker-образа с тегом "mini_project_backend_rds" из Dockerfile в папке backend_rds.

      # Step 3: Build Docker image for backend_redis
      - name: Build Docker Image for Backend Redis
        run: |
          docker build -t mini_project_backend_redis -f backend_redis/Dockerfile backend_redis
          # Сборка Docker-образа с тегом "mini_project_backend_redis" из Dockerfile в папке backend_redis.

      # Step 4: Deploy to AWS EC2
      - name: Deploy to AWS EC2
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > ssh_key.pem
          chmod 400 ssh_key.pem
          scp -o StrictHostKeyChecking=no -i ssh_key.pem docker-compose.yml ec2-user@51.17.222.95:/home/ec2-user/mini_project_1_v26/
          ssh -o StrictHostKeyChecking=no -i ssh_key.pem ec2-user@51.17.222.95 "cd /home/ec2-user/mini_project_1_v26 && docker-compose down && docker-compose up -d"
          # Копирование файла docker-compose.yml на EC2 и перезапуск Docker-контейнеров для обновления приложения.
